name: docker-build-prod-ci
on:
  push:
    branches: 
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "BUILD_DATETIME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yt-dlp:${{ env.BUILD_DATETIME }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yt-dlp:latest
      - 
        name: discord notification
        uses: docker://alicey/gha2discord:latest
        env:
          WEBHOOK_URL: ${{ secrets.DC_WEBHOOK_URL }}
          MESSAGE_USERNAME: "GitHub Actions"
          MESSAGE_AVATAR_URL: ""
          MESSAGE_AUTHORNAME: "Docker Push"
          MESSAGE_AUTHORICON_URL: ""
          MESSAGE_COMMENT: "[Prod]\n${{ secrets.DOCKERHUB_USERNAME }}/yt-dlp:${{ env.BUILD_DATETIME }}"
        with:
          entrypoint: "python3"
          args: "/opt/app/app.py"